# Generated by Django 4.2.6 on 2023-11-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filestatements_created_at_filestatements_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filestatements',
            options={'ordering': ['-created_at', '-year']},
        ),
        migrations.AddField(
            model_name='filestatements',
            name='year',
            field=models.IntegerField(blank=True, default=2022),
            preserve_default=False,
        ),
    ]
