# Generated by Django 4.2.6 on 2023-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_filestatements_options_filestatements_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filestatements',
            options={'ordering': ['-created_at', '-year'], 'verbose_name': 'File Statement', 'verbose_name_plural': 'File Statements'},
        ),
        migrations.AddField(
            model_name='filestatements',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
